import { NextResponse } from 'next/server';

const mockGrants = [
  {
    id: '1',
    title: 'National Lottery Community Fund',
    amount: 10000,
    status: 'researching',
    deadline: new Date('2025-06-30').toISOString(),
    description: 'Funding for community projects that matter',
    eligibility: 'UK registered charities and non-profit organisations',
    applicationDetails: 'Online application required with project plan',
    logo: '/images/lottery.png',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '2',
    title: 'The Fore',
    amount: 15000,
    status: 'eligible',
    deadline: new Date('2025-04-28').toISOString(),
    description: 'Supporting innovative solutions to social issues',
    eligibility: 'Small charities and social enterprises',
    applicationDetails: 'Two-stage application process',
    logo: '/images/fore.png',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '3',
    title: 'King Charles III Charitable Fund',
    amount: 25000,
    status: 'applied',
    deadline: new Date('2025-05-15').toISOString(),
    description: 'Supporting environmental and community initiatives',
    eligibility: 'UK registered environmental charities',
    applicationDetails: 'Detailed project proposal required',
    logo: '/images/king.png',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '4',
    title: 'Greggs Foundation',
    amount: 5000,
    status: 'successful',
    deadline: new Date('2025-04-18').toISOString(),
    description: 'Local community projects funding',
    eligibility: 'Local community organisations',
    applicationDetails: 'Simple online application',
    logo: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '5',
    title: 'Matthew Good Foundation',
    amount: 7500,
    status: 'unsuccessful',
    deadline: new Date('2025-04-01').toISOString(),
    description: 'Supporting grassroots charities',
    eligibility: 'Small UK charities with annual income under £50,000',
    applicationDetails: 'Monthly grant rounds',
    logo: '/images/matthew.png',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '6',
    title: 'The Leathersellers\' Company',
    amount: 12000,
    status: 'researching',
    deadline: new Date('2025-09-30').toISOString(),
    description: 'Supporting UK charities and educational initiatives',
    eligibility: 'UK registered charities working with disadvantaged communities',
    applicationDetails: 'Rolling programme with 8 application windows per year',
    logo: '/images/leathersellers.png',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '7',
    title: 'Trusthouse Charitable Foundation',
    amount: 20000,
    status: 'eligible',
    deadline: new Date('2025-05-02').toISOString(),
    description: 'Supporting rural and urban communities',
    eligibility: 'UK charities and not-for-profit organisations',
    applicationDetails: 'Online application with detailed project budget required',
    logo: '/images/trusthouse.webp',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '8',
    title: 'The Clothworkers\' Foundation',
    amount: 30000,
    status: 'applied',
    deadline: new Date('2025-07-30').toISOString(),
    description: 'Capital grants for UK charities',
    eligibility: 'UK registered charities with annual income under £2 million',
    applicationDetails: 'Two-stage application process for capital projects',
    logo: '/images/clothworkers.png',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '9',
    title: 'UK Community Foundations',
    amount: 8000,
    status: 'researching',
    deadline: new Date('2025-10-15').toISOString(),
    description: 'Local funding for community initiatives',
    eligibility: 'Community groups and small charities',
    applicationDetails: 'Application through local Community Foundation',
    logo: '/images/community.png',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '10',
    title: 'Garfield Weston Foundation',
    amount: 40000,
    status: 'eligible',
    deadline: new Date('2025-09-01').toISOString(),
    description: 'Supporting charities across the UK',
    eligibility: 'UK registered charities',
    applicationDetails: 'Regular grants programme with online application',
    logo: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '11',
    title: 'The Tudor Trust',
    amount: 35000,
    status: 'applied',
    deadline: new Date('2025-08-30').toISOString(),
    description: 'Core funding for voluntary and community groups',
    eligibility: 'UK organisations working for positive social change',
    applicationDetails: 'Two-stage application process with initial proposal',
    logo: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '12',
    title: 'Esmée Fairbairn Foundation',
    amount: 50000,
    status: 'researching',
    deadline: new Date('2025-11-15').toISOString(),
    description: 'Supporting social change and environmental protection',
    eligibility: 'UK organisations with clear social impact',
    applicationDetails: 'Expression of interest required before full application',
    logo: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '13',
    title: 'Lloyds Bank Foundation',
    amount: 25000,
    status: 'drafting',
    deadline: new Date('2025-07-15').toISOString(),
    description: 'Supporting small and local charities',
    eligibility: 'UK charities with income under £1 million',
    applicationDetails: 'Two-stage application process with development support',
    logo: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
  {
    id: '14',
    title: 'The Wolfson Foundation',
    amount: 35000,
    status: 'drafting',
    deadline: new Date('2025-08-20').toISOString(),
    description: 'Capital funding for charities and educational institutions',
    eligibility: 'UK registered charities and educational institutions',
    applicationDetails: 'Detailed project proposal and budget required',
    logo: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    projects: [],
  },
];

export async function GET() {
  return NextResponse.json(mockGrants);
}

export async function POST(request: Request) {
  try {
    // In demo mode, we just return a success response
    return NextResponse.json({ success: true, message: 'Grant created successfully (Demo)' });
  } catch (error) {
    console.error('Error creating grant:', error);
    return NextResponse.json(
      { error: 'Failed to create grant' },
      { status: 500 }
    );
  }
} 